### ISSUE TITLE
Viterbi hangs if it does not find a valid path

### ISSUE THREAD

**Issue by flokadillo** [CPJKU/madmom#100]
Right now the Viterbi hangs if it cannot find a valid state sequence. This is because `bt_pointers` are initialised as np.empty and in the backtracing step we try to access values that were not initialised:
`state = bt_pointers[frame, state]`

Solution: Initialise `bt_pointers` with np.zeros instead of np.empty.

In addition it would be nice to throw an error if no valid sequence can be found.
E.g. before backtracing:

```
if np.isinf(np.asarray(current_viterbi).max()):
            raise ValueError('Invalid state sequence found')
```

**Comment by superbock** [comment]
I see the problem, but I'm not sure if initialising `bt_pointers` with zeros is the right solution since `0` is a valid state number and this would mean that you get a wrong path.

I think it is better to raise an error, but I'm not sure where. Some thoughts:

* should it be ok for some states to not be able to determine a valid previous state?
* or should we raise an error as soon as there isn't?
* is line 402 in `hmm.pyx` too early to raise an error?

**Comment by fdlm** [comment]
IMHO the correct behaviour should be:

 1. Raise an error if this happens. Viterbi not finding a correct path is not a valid outcome of the algorithm, but a numerical problem caused by the observation probabilities being to small.
 2. Allow overcoming this problem by adding a very small value to the observation probabilities. This could be a parameter of the observation model.

I think we can only catch the error reliably by either

 - checking if all values `current_viterbi`are invalid at every iteration, or
 - checking in the end if `log_probability` is valid.

I favour the second option, because it does not add runtime overhead for every run.

**Comment by flokadillo** [comment]
* it is ok for some states not to have a valid previous state, but if this prevents us from finding a single valid state sequence we should raise an error.
* I agree with Filip that we could just check at the end if `log_probability` is valid 
* adding a small value to the observation probability would be a solution but this should not be done in the `viterbi` function, maybe in the observation model and transition model as Filip said.

**Comment by superbock** [comment]
Ok, where are we on this? Should we return an empty array (i.e. no path) and -inf log probability if the log probability is -inf? This can be accomplished at basically 0 cost, since we have to to this check only once before returning `(path, log_probability)`.

**Comment by fdlm** [comment]
I would at least issue a warning (similar to a division by 0 warning)
