### ISSUE TITLE
Sound Pressure Level and RMS should be computable on FramedSignals

### ISSUE THREAD

**Issue by fdlm** [CPJKU/madmom#114]
Right now, it is only possible to compute SPL and RMS on the whole signal. It should also work on `FramedSignal` instances, where the function returns a SPL/RMS value for each frame.

**Comment by superbock** [comment]
Yes, absolutely! We have the following possibilities:

1. change the function to test the type of input
2. add a `spl()` and `rms()` methods to the `FramedSignal`
3. define classes `SPL` and `RMS` classed which could return the right values

I prefer 2. or 3. since it keeps the function to work an simple arrays only.
