### ISSUE TITLE
GMMPatternTracker with downbeats flag

### ISSUE THREAD

**Issue by srviest** [CPJKU/madmom#127]
I tried the GMMPatternTracker executable with --downbeats flag like this:

$ GMMPatternTracker --downbeats single input.wav output.txt

The expected output should be all the downbeats of time instants. However, all the things I got was just 2 float values, is this a bug?

**Comment by superbock** [comment]
First of all, please call the program with `GMMPatternTracker --downbeats single input.wav -o output.txt`, otherwise it does not write the output to `output.txt`. Note the `-o` option, which changed some time ago (in commit d57547603). If the old calling scheme is still mentioned somewhere, please let me know.

But this is not the problem you are referring to. Unless you provide a link to the use audio file, there is no way to determine if this is the expected output or not. The expected output is a list of timestamps of the downbeats, i.e. only the first column of the lines ending with 1 when being called without the `--downbeats` option.

You can check if the `GMMPatternTracker` works properly on your system or not by running the included tests. If you have the sources checked out, just run `nosetests` in the root directory of the repo. Please note that tests for the programs in `/bin` were added only recently, so I advise to update madmom first, i.e. do a `git pull` followed by a `git submodule update`.

**Comment by superbock** [comment]
Just an additional note, please be aware that the `GMMPatternTracker` uses only rhythmic patterns learnt from Ballroom dance music to detect the beats and downbeats. It might not work well for other type of music.

P.S. stay tuned for a general purpose downbeat tracker I will add soon

**Comment by srviest** [comment]
Opps, sorry for the typo. 
I called the` GMMPatternTracker `by `GMMPatternTracker single input.wav -o output.txt`.
And it returned output like:
0.320	1
1.040	2
1.760	3
2.480	4
3.200	1
3.900	2
4.600	3
5.300	4
....and so on.

But when I called the program with `--downbeats`, it just returned:
0.320
1.000

**Comment by superbock** [comment]
This is clearly a bug, I'll look into it. Thanks for reporting!

**Comment by superbock** [comment]
Should be fixed in the `fix_downbeat_output` branch (PR #128). The issue will be closed when I merge this, please feel free to reopen the issue if it does not solve your problem.

**Comment by superbock** [comment]
FYI: I merged the RNN/DBN downbeat tracking stuff mentioned above.
