### ISSUE TITLE
Citing madmom

### ISSUE THREAD

**Issue by sertansenturk** [CPJKU/madmom#229]
Hi madmom people,

In the toolbox documentation, I was not able to locate any reference to your paper hosted in [arxiv](https://arxiv.org/abs/1605.07008). I thought that you would like to add that to the README, in case it's forgotten during the busy development cycle :)

Also, you might also want to consider adding the repository to Zenodo (https://guides.github.com/activities/citable-code/). This way the specific releases may be cited properly in the future. You can even do *fancy* stuff in Zenodo such as linking the DOI with arxiv entry and even notfying the funding agency automatically (for EU projects).

**Comment by superbock** [comment]
There's an updated version of the paper published at ACM Multimedia which already has a DOI (http://dx.doi.org/10.1145/2964284.2973795), unfortunately it is not accessible without a subscription.

I hope to find some time to update the arXiv version to reflect all the changes made for the Multimedia version. Unfortunately again it is a bit complicated, since there are code examples in there which require Latex to be run with shell escape flags -- which arXiv does not support.

Thanks for the reminder!

**Comment by sertansenturk** [comment]
Thanks Sebastian, I'll update the entry in the bibliography of my thesis :)
