### ISSUE TITLE
ffmpeg.py does not check for unicode strings

### ISSUE THREAD

**Issue by flokadillo** [CPJKU/madmom#241]
In ``madmom.audio.ffmpeg.py``, there are several lines where ``isinstance(infile, str):`` is used. We should replace this by ``isinstance(infile, (str, unicode)):`` to also support python 2.7's unicode string type.

**Comment by superbock** [comment]
Actually, it is only a single line (https://github.com/CPJKU/madmom/blob/master/madmom/audio/ffmpeg.py#L170), but using the above suggestion breaks Python 3, since it does not have ``unicode`` type any more.

Can you provide an example (or even better: a test) which shows the problem? I fixed something related quite recently #236. Seems like this fix was not enough.

**Comment by flokadillo** [comment]
Actually, this happens also in line 184, 243, and 292.
Here is a small example:
`from madmom.audio.ffmpeg import decode_to_memory`
`infile = u'C:\\Users\\krf\\dev\\python\\madmom\\tests\\data\\audio\\sample.wav'`
`s=decode_to_memory(infile)`
This produces the following error:
`ValueError: only file names or Signal instances are supported as `infile`, not C:\Users\krf\dev\python\madmom\tests\data\audio\sample.wav.`
Maybe we have to add an if clause to check types for different versions of Python...

**Comment by superbock** [comment]
@flokadillo, could you try the fix provided in #305 and see if it fixes your issue?
