### ISSUE TITLE
hopSize of Spectral Flux

### ISSUE THREAD

**Issue by georgid** [CPJKU/madmom#270]
I have one doubt about the hopSize of the spectral Flux feature. The default (I guess optimal) hopSize in madmom is 0.02 s, whereas the optimal one for another feature (pitch) feature is 0.0058. I have to come up with a strategy to integrate the two for simultaneous note onset and beat detection.  I evaluated the note segmentation step increasing the default hopsize of 0.0058 (256/44100 samples) to 0.02 (the default in madmom) sec. This results in less onsets detected and very big decrease of recall, so not desirable idea. Instead I am thinking of  using a hopsize of 0.0058 on decoding the beats, e.g. around 172 fps.  Do you know if decreasing the hopSize of the spectral flux that much makes sense ? I am concerned that while computing the flux, the spectral difference to previous window depends on the hopSize, right?   
 have you done any experiments on the effect of different hopSizes on the performance of downbeat tracking ?

**Comment by superbock** [comment]
First of all, there's no such thing as the default (or even optimal) `hop_size`. madmom usually relies on setting the frames per second (`fps`), because it is independent of the sample rate of the signal. The default `fps` is 100. There are a couple of exceptions to this rule, e.g. `SuperFlux` uses 200 fps, `DeepChromaProcessor` uses 10 fps, `GMMPatternTracker` uses 50 fps, but most algorithms use 100 fps.

I am not sure how you think the default (computed) hop size is 0.02 s (which corresponds to 50 fps), so I have to guess that you refer to the `GMMPatternTracker`. Since this is @flokadillo's work, I have no idea on how using a higher frame rate works or not. I never used spectral flux like features for (down-)beat tracking directly, only as inputs to neural networks and there 100 fps seems to be some kind of sweet spot for the frame rate.

To answer the question whether decreasing the hop size for spectral flux makes sense, I think `SuperFlux` is a good example that you can do this without any negative effect. Instead of calculating the flux to the previous frame, it uses a parameter called `diff_ratio` which calculates the number of frames based on the hop size / frame rate. Maybe you can use something similar.

P.S. it wouldn't hurt to first describe what you want to accomplish and then give detailed information on the problem before submitting a new issue -- at least it would make understanding and helping with the issue much easier...

**Comment by superbock** [comment]
Gonna close this, since it is not an issue.
