### ISSUE TITLE
HMM Viterbi bug if last state of TransitionModel is unreachable

### ISSUE THREAD

**Issue by fdlm** [CPJKU/madmom#285]
Related to #283. If the last state of an HMM is unreachable, `TransitionModel.pointers` does not have an element for it (which caused #283). However, `HiddenMarkovModel.viterbi` accesses it:
```python
                for pointer in range(tm_pointers[state],
                                     tm_pointers[state + 1]):
```
This out-of-bounds access can lead to segmentation faults.

If the unreachable state is not the last, there is no problem. This is caused by the sparsification procedure. For example, try the following transition matrices, where either the first or second state are unreachable, and look at the `pointers` in the `TransitionModel`:
```python
A_f = np.array([[0.0, 1.0], [0.0, 1.0]]) # first unreachable
A_s = np.array([[1.0, 0.0], [1.0, 0.0]]) # second unreachable
ff, tf = A_f.nonzero()
fs, ts = A_s.nonzero()
print TransitionModel.from_dense(tf, ff, A_f[ff, tf]).pointers
print TransitionModel.from_dense(ts, fs, A_s[fs, ts]).pointers
```
This will output
```
[0 0 2]
[0 2]
```
The second case does not work, because `viterbi` will access the `pointers[2]` in the loop shown above.

A workaround would be if we check for this in `TransitionModel.make_sparse`, and add a dummy pointer that ensures that no alleged previous states are processed. This would also deprecate #284.

Any better ideas? 

*Update:* sample code was wrong.

**Comment by superbock** [comment]
I think I see the problem, but unfortunately I cannot reproduce it with the code given above. `TransitionModel.from_dense(ff, tf, A_f[tf, ff]).pointers` gives me a `ValueError: Not a probability distribution.`. Using `TransitionModel.from_dense(tf, ff, [1, 1])` gives at least the expected output.

If I get this correctly, the problem occurs if there are states which a probable because of the observation model (or initial distribution or whatever), but for which no transitions from other sates are possible. Then `csr_matrix` simply omits these states, although they should be kept.

As you suggested, adding dummy entries to `pointers` could solve the problem. For the example given in #283, `pointers` should be `[0, 3, 6, 6]` instead of `[0, 3, 6]` which would also solve the `num_states` problem. However, I'm not sure if this can only happen if there are no transitions to the last state, or if this problem persists (with the suggested workaround) if any other state is not reachable.

**Comment by fdlm** [comment]
The code did not work because I mixed up `tf` and `tt`. Sorry about that, it should work now.

The root of the problem is that if the last column of a transition matrix is empty (thus the last state is unreachable), there is no entry in the `states` parameter for this state, and therefore `csr_matrix` assumes this row does not exist. Thus, the `csr_matrix` is not square anymore (it is, in our case, a `1x2` matrix).

This can be easily prevented by passing the shape of the matrix (which must be square!) to `csr_matrix`. Then, `pointers` looks just like you described it. I will create a PR for this soon. The old one, #284, is thus obsolete.
