### ISSUE TITLE
[Q] Online onset detection with frequency band?

### ISSUE THREAD

**Issue by gregfriedland** [CPJKU/madmom#318]
Hello,
First off, thanks for opening up the source of your library to the community. I've built a few LED art projects and programmed my own rough attempt at music responsiveness for them (e.g. https://youtu.be/BarnvIDiebg?t=179). I was glad to discover your library and hope to use it to add more effective music responsiveness to my next project. 

I've looked over the examples in the bin direction and have a few questions:
- Is there a method that will provide the frequency band associated with onsets during online use? The precise midi note would be great but even a rough category like treble, mid, or bass would be sufficient. I have written some dynamic patterns (e.g. https://mrob.com/pub/comp/xmorphia/F180/F180-k570.html) that I'd love to be able to sync to music such that different frequencies trigger different visual responses.
- Related to the previous q: Are there plans to add online processing to PianoTranscriptor?

Cheers,
Greg

**Comment by superbock** [comment]
There is no pre-defined method to obtain the most salient frequency bands together with the onsets. However, it is really easy to accomplish something like this if simple spectral based onset detection (i.e. [`bin/SpectralOnsetDetection`](https://github.com/CPJKU/madmom/blob/master/bin/SpectralOnsetDetection)) is "enough" for your purpose.

The `SpectralOnsetProcessor` does nothing more than creating a logarithmically filtered and scaled spectrogram, computes the bin-wise differences and then sums all positive differences. You could then simply define your own onset detection method (similar to [`spectral_flux`](https://github.com/CPJKU/madmom/blob/master/madmom/features/onsets.py#L164) or [`superflux`](https://github.com/CPJKU/madmom/blob/master/madmom/features/onsets.py#L197)) which additionally returns all or only the relevant bin(s) with the highest value(s)  (e.g. as a tuple) and pass this function to `SpectralOnsetProcessor` [in line 99 of `bin/SpectralOnsetDetection`](https://github.com/CPJKU/madmom/blob/master/bin/SpectralOnsetDetection#L99).

Of course you have to alter the peak picking accordingly, but again this is really easy. Simply make your own class inheriting from [`OnsetPeakPickingProcessor`](https://github.com/CPJKU/madmom/blob/master/madmom/features/onsets.py#L1021), which first splits the received tuple into the two parts and call `super()` on the first item and process the second item as you like. Of course you can also combine all the functionality in a single class and use that instead.

As for your second question, there are no plans to add online processing to PianoTranscriptor simply because it is technically not possible. PianoTranscriptor relies on bidirectional neural networks, i.e. the network processes the audio frames both in forward and backward direction (like playing the music backwards).

HTH

**Comment by gregfriedland** [comment]
Great! Thanks for the detailed pointers. I will try that out.

One quick question: SpectralOnsetDetection doesn't seem to currently accept 'online' so I added online=True to io_arguments(...) in there but then `./bin/SpectralOnsetDetection --odf spectral_flux online` still doesn't create any output from microphone input (even while `./bin/OnsetDetectorLL online` does). Is there something else I need to change in SpectralOnsetDetection?

**Comment by superbock** [comment]
The reason it doesn't have the `online` mode is simply that it does not work yet 😏 Sorry, I totally forgot about that.

The problem is that the onset detection functions use 'data-classes' instead of processors (i.e. `SpectrogramDifference` instead of `SpectrogramDifferenceProcessor`), and thus are not able to not keep their state. If these functions are called with a single frame, they simply don't have enough context to correctly compute the differences — they need to have at least the last frame around (what the processor does), otherwise the diff is always 0.

Adding online mode to these onset detection functions is on my TODO list and I might have time to do this in the next weeks (without guarantee).

But maybe this gets you started quickly:
```
class SpectralFluxProcessor(SequentialProcessor):

    def __init__(self):
        from functools import partial
        from madmom.audio.spectrogram import SpectrogramDifferenceProcessor
        diff = SpectrogramDifferenceProcessor(diff_frames=1,
                                              positive_diffs=True)
        sum = partial(np.sum, axis=1)
        super(SpectralFluxProcessor, self).__init__([diff, sum])
```

Simply insert this processor at the end of `SpectralOnsetProcessor` instead of the odf stuff. Then it should work.

**Comment by gregfriedland** [comment]
Thanks, that got me pretty far. :) I now have online onset detection working with spectral_flux from `SpectralOnsetDetection` in my fork. Well it kind of works... The onset detection is noticeably delayed (by maybe a few hundred ms) when I tap on the mic with my finger; something I don't notice when running `OnsetDetectorLL online`. Does that make any sense? My changes are https://github.com/gregfriedland/madmom/commit/af52db1789123e9a4884ccab329e3e9ee1a31347

**Comment by superbock** [comment]
Does this make sense? yes and no 😄 

From the usability perspective: definitely no. From the code perspective: unfortunately yes.
The problem is that your code actually calls `ffmpeg` to perform a sample rate conversion. This causes the delay. The easiest (and hopefully correct) solution is to to change [line 763 of `Signal`](https://github.com/CPJKU/madmom/blob/master/madmom/audio/signal.py#L763) to:

```
if sample_rate and sample_rate != data.sample_rate:
```

This invokes a sample rate conversion only if there's a desired sample rate set.

**Comment by gregfriedland** [comment]
Perfect, I got it working now. And I was able to outputting the frequency of each onset. Thanks for your help. :) I'll try to post a video of the final project when I'm done.
