### ISSUE TITLE
Quantize Events - Wrong dimensions returned.

### ISSUE THREAD

**Issue by Reichenbachian** [CPJKU/madmom#325]
I'm trying to read and quantize a midi file.
```
madmom.utils.quantize_events(madmom.utils.midi.MIDIFile.from_file('http:..www.jsbach.net.midi.bwv996.mid.mid').notes(), 100)
```
This returns a one-dimensional list of float64s. The description, as per the documentation, says it returns the events. I'm a bit confused as to the output here.

**Comment by superbock** [comment]
Thanks for pointing this out!

The functions is only supposed to operate on 1-dimensional input data, but fails to check the dimensionality and raise an error. Still this function contains another bug, since it alters the given array, which it definitely should not (fixed in 3baefc7)

But put this aside, what output did you expect?

For 1D inputs, the expected output is clear, but for 2D inputs it is much more difficult.

Since quantisation makes the resulting array much bigger, there's the optional `length` argument which takes care of how big the returned array should be. If it is not set it looks for the max. value of events and sets the length accordingly.

Something similar would be needed for the second dimension. E.g. for piano MIDI notes containing only onsets and pitch information, the resulting array would have the same length as for 1D inputs, and the second dimension would be expanded to 88 columns representing the notes.

If additionally the length is given, that could be quantised as well. And the velocity information could be incorporated as the target values for the quantised bins.

This is basically the only way I can think of quantising note events. Is this what you expected the function to return?

**Comment by Reichenbachian** [comment]
Yes. That's the same way I was thinking. I'm trying to quantize a many piano MIDI files into np arrays(to input into keras).

My ideal output for this function would be an array of 88xquantization*length. That doesn't seem much harder, as you're not really quantizing the second dimension(88). It might even be as easy as a wrapper around the 1d quantization. I'm still a bit confused as to what the 1d quantization does, so I'll read the code and see if I can whip up a wrapper. Any help or advice would be greatly appreciated, though!

**Comment by superbock** [comment]
I think I will add a `quantize_notes` function that does exactly that.

**Comment by Reichenbachian** [comment]
It would be very much appreciated. Thank you for your quick responses.

**Comment by Reichenbachian** [comment]
Was this function ever made?

**Comment by superbock** [comment]
It is done, but needs more testing and unit tests. I pushed the function to the `fix_325` branch (see 24cfea40b in PR #327), but please be aware that it is not fully tested yet. Please let me know if you encounter any problems or if the function does what you originally intended.

**Comment by superbock** [comment]
Just a heads up: #327 was merged, but the function signature did change a bit since that commit. Please make sure that your code works with the final version of `qantize_notes`.
