### ISSUE TITLE
Installation from source fails on Ubuntu 16.04 - wrong import in setup.py?

### ISSUE THREAD

**Issue by nullmightybofo** [CPJKU/madmom#332]
*update, also see my answer below*

Hi!

I tried to install madmom from source today (*) on Ubuntu 16.04, following these installation instructions: 

https://github.com/CPJKU/madmom#install-from-source

(* with the code cloned today, master branch.)

`python setup.py develop --user` fails with an ImportError saying it cannot import `build_ext`. 

I figured out that the problem seems to be this line in setup.py:

https://github.com/CPJKU/madmom/blob/48c11ad5dbea843c47c81bfcc7ba366663a424b0/setup.py#L12

`from Cython.Build import cythonize, build_ext`

Changing it to:

`from Cython.Build import cythonize`
`from Cython.Distutils import build_ext`

makes the installation work and fixes the problem for me. The test (python setup.py test) works Ok as does import of the package in python 2.7.

If you need any further information, shoot!

**Comment by nullmightybofo** [comment]
I see that this line was changed in this commit:

https://github.com/CPJKU/madmom/commit/96d1239f5b845e5318430a27bf5697078a2a0884

I made sure that the packages are newer than the ones stated in "requirements.txt".  In particular, I have cython version '0.23.4' whereas requirements says >= 0.22.1 (I think cython seems to be the problem here).

cython 0.23.4 is the default version for Ubuntu 16.04:
https://packages.ubuntu.com/xenial/cython

**Comment by superbock** [comment]
The problem is that Cython 0.25 changed the build system and makes the old way not work any more. 96d1239 changed it to work with newer version (for discussion see #225). However, we forgot to update `requirements.txt` to reflect this change.

What you propose is to change it back to the old style, which fixes it only for old Cython versions, but won't work for newer Cython versions. Ok, it might still work since 0.25.1 reverted some of the changes, but still this way is deprecated.

So the correct solution is to either bump the required version (0.23.4 is almost 2 years old) or use a try/except clause to import `build_ext`. Given the long list of fixed bugs ([see Cython's release notes](https://github.com/cython/cython/blob/master/CHANGES.rst)) I am however not sure if it is worth the hassle and simply bumping the required version is less error prone in the long run.

Anyways: the easiest (and future proof) fix for you is to update your Cython version.

HTH
