### ISSUE TITLE
FramedSignalProcessor ignores the kwargs during initialization

### ISSUE THREAD

**Issue by 183amir** [CPJKU/madmom#339]
### Expected behaviour

[FramedSignalProcessor](https://madmom.readthedocs.io/en/latest/modules/audio/signal.html#madmom.audio.signal.FramedSignalProcessor) should pass the kwargs to the `Signal` class if the input is not already a `Signal`.

### Actual behaviour

The kwargs passed during initialization is ignored.

### Steps needed to reproduce the behaviour

```python
from madmom.audio import Signal, FramedSignal
from madmom.audio import FramedSignalProcessor
import numpy as np

path = 'A 48Khz audio'

signal = Signal(path, sample_rate=16000)
fsignal_correct = FramedSignal(signal)

fsig_proc = FramedSignalProcessor(sample_rate=16000)
# sample_rate is just ignored here while the docs says it is used to initialize Signal.
fsignal_wrong = fsig_proc(path)

np.allclose(fsignal_correct, fsignal_wrong)
```

Either the documentation is wrong or this is a bug.

### Information about installed software

Python 3.5, numpy 1.12.1, madmom 0.15.1, and scipy 0.19.0

**Comment by superbock** [comment]
Thanks for reporting this! Here the documentation is wrong -- most probably a copy/paste error of docstrings from `FramedSignal` to its corresponding processor.

Only data class support argument passing, mostly to allow rapid prototyping, e.g. to be able to instantiate a spectrogram from a filename. I.e. the following also produces the same frames:

```python
fsignal = FramedSignal(path, sample_rate=16000)
```

When using processors, you have to define all intermediate steps as processors as well and pass the arguments explicitly. E.g.:

```python
sig_proc = SignalProcessor(sample_rate=16000)
fsig_proc = FramedSignalProcessor()
proc = SequentialProcessor([sig_proc, fsig_proc])
fsignal = proc(path)
```
 
Please note that processors ignore additional arguments (that's what happens in your case 😏) in order to be able to define a processing chain and simply pass the same arguments as dictionary to all of them.

Will fix the docstrings.

**Comment by 183amir** [comment]
It's a bit weird because `FilteredSpectrogram` for example does take kwargs into account.

**Comment by 183amir** [comment]
Never mind! I thought I am looking at `FilteredSpectrogramProcessor`

**Comment by 183amir** [comment]
Maybe in processor versions you point the original class instead of documenting things again and maintaining in two places?

**Comment by 183amir** [comment]
Okay I see that those arguments are handled differently like `kwargs` so maybe its better to document them twice.
