### ISSUE TITLE
Faster downbeat detection?

### ISSUE THREAD

**Issue by keunwoochoi** [CPJKU/madmom#340]
Hi, I was wondering if I could tweak the code so that the RNN-based downbeat detection could become faster. ..by using Lower FPS and smaller number of band, and perhaps downsample the signal to some extent. But I'm afraid it won't make sense since RNN was trained with those parameters. Am I correct?

I was also thinking if I'd trained one by myself. If all the dataset were nicely merged into one, I'd be already doing it.. :(

**Comment by superbock** [comment]
You are absolutely right, there's not really a way to make the RNN faster since it is trained exactly with these parameters.

What runtime did you expect? On my computer (a rather dated Macbook from 2014) processing of 60 seconds of audio takes less than 8 seconds, which is 7.5 times real-time.

If this is still to slow for you you can try to evaluate only a couple of RNNs and not all of them (e.g. alter `DOWNBEATS_BLSTM` in `madmom/models/__init__.py`) or limit the number of tempo states for the DBN (could be done via command line). Both measures will make downbeat tracking faster but less accurate.

The easiest solution is to buy a faster machine ;)

**Comment by keunwoochoi** [comment]
There's no strict target speed, just wondered if there could be some workaround, the current version is still fine though.

Thanks!
