### ISSUE TITLE
hist_smooth in the TempoEstimationProcessor is ignored

### ISSUE THREAD

**Issue by JasperStam** [CPJKU/madmom#349]
### Expected behaviour

I have a 90second audio file, and I want to measure the BPM of each 10 second fragment.
I created a TempoEstimationProcessor with hist_smooth=9

### Actual behaviour

It returned a list of len 7, so 7 bins.

### Steps needed to reproduce the behaviour

```python
from madmom.features.beats import RNNBeatProcessor
from madmom.features.tempo import TempoEstimationProcessor

proc = TempoEstimationProcessor(fps=60, hist_smooth=9)
act = RNNBeatProcessor()('./input.mp3')
```

### Information about installed software

madmom version: 0.15.1
numpy version: 1.13.3
scipy version: 1.0.0

**Comment by superbock** [comment]
Unfortunately the example misses some information, but lets assume you feed `act` into `proc`, i.e. `proc(act)`.

There are a couple of misconceptions I guess. First of all, `hist_smooth` smooths the **bins** of the tempo histogram. These bins correspond to tempo values (more precisely: the inter beat intervals) and are computed for the given input signal. Histogram smoothing has nothing to do with time, it just helps to smooth out small/narrow gaps in the tempo histogram which can occur if a tempo of the input signal has some jitter around the mean tempo.

There's also the problem that `RNNBeatProcessor` always produces a beat activation function sampled at 100 frames per second. Thus `TempoEstimationProcessor` is must have the same `fps` as the signal fed into it (100 fps). You cannot use arbitrary values, since `fps` is needed to translate from inter beat intervals in frames per second (fps) to tempo in beats per minute (bpm).

As mentioned above, `TempoEstimationProcessor` estimates the tempo of the entire input signal. Thus the output is not related to time at all. The result you get should be a 2D array (and not a list) with tempi (in bpm) as the first column and their strengths as the second column. I admit that the docstrings could be a bit more descriptive, but both `process_offline` and `process_online` clearly state what the processor returns when being called.

Anyways, what you probably want to accomplish can't be done the way you tried it, because you manually have to split `act` into segments of 10 seconds length and estimate the tempi for these segments individually. `FramedSignalProcessor` can help to chop `act` into segments (wrap `act` as a `Signal` first ([see this example](https://github.com/CPJKU/madmom/blob/master/madmom/audio/chroma.py#L263)).

Please be aware that most tempo estimation methods need a certain "warm-up time", i.e. they might not be able to report good tempo estimates for short segments. Perhaps `DBNTempoHistogramProcessor` (already in `mater` branch, to appear in the next release) is closer to what you are looking for. [Have a look at line 551](https://github.com/CPJKU/madmom/blob/master/madmom/features/tempo.py#L551) where the (beat) intervals for every single frame are computed. You might be able to use this information and chop it into segments and then simply smooth the histogram and detect the tempo for all segments.

HTH

**Comment by JasperStam** [comment]
Thanks for the help! Will check it out
