### ISSUE TITLE
DBNDownBeatTrackingProcessor issue

### ISSUE THREAD

**Issue by bzvew** [CPJKU/madmom#366]
### Expected behaviour

Beat of the songs should be the same if it does not change.

### Actual behaviour

Using DBNDownBeatTrackingProcessor, the beat doubles after the middle part of the song tested here. https://drive.google.com/open?id=1B8HbFLn4TBz2i9TGs7eacCrMLjz4dR03

**Comment by superbock** [comment]
This is not an issue with `DBNDownBeatTrackingProcessor` per se, since it works perfectly fine, i.e. it correctly tracks the beats and downbeats given the inputs and parameter settings.

Your 'issue' is that that output does not match your expectations. This is simply due to the fact that `RNNDownBeatProcessor` has a different understanding about beats and downbeats and outputs probabilities that lead to that result. More specifically, the predictions of the neural network ensemble leads to these output.

You have a couple of options to solve this 'issue':
- limit the tempo range, e.g. set `max_bpm` to 100 or something like this
- increase `transition_lambda` to prefer constant tempi over tempo changes
- try using only a certain neural network model or a combination of several models; unfortunately this is not doable via arguments yet, you have to modify `DOWNBEATS_BLSTM` directly
- train your own model which outputs better activations for this kind of music

HTH

**Comment by bzvew** [comment]
I try observation_lambda=300 and the tempo keeps the same, great!
