### ISSUE TITLE
ValueError when creating spectogram

### ISSUE THREAD

**Issue by bjourne** [CPJKU/madmom#411]
Im running

    spec = madmom.audio.spectrogram.Spectrogram(path)

And I get the traceback:

    ValueError: frames must be a 2D array or iterable, got <class 'madmom.audio.signal.FramedSignal'> with shape (6555, 2048, 2).

Version of madmom is 0.17.dev0 installed directly from github.

**Comment by bjourne** [comment]
When I test with another wav file it works. Is madmom not able to read stereo data or something?

**Comment by superbock** [comment]
It is, but you have to tell madmom how to handle multiple channels, i.e. let it downmix stereo signals to mono y passing `num_channels = 1` or specify which `channel` to use.

If you want to have stereo spectrograms, there's not a single answer on how this should be handled. Please see #371 for details. This issue is still open, so please add your input there if you need multi-channel STFT/spectrograms.
