### ISSUE TITLE
Accurate Tempo Estimation

### ISSUE THREAD

**Issue by louischaman** [CPJKU/madmom#416]
I'm developing a tool that makes use of madmom to generate a Syncronised beat clock to a live audio signal of a track with fixed BPM. 

The approach is to record some audio, estimate bpm and beat positions and then generate positions of all future beats. 

I have found the methods that come with madmom for tempo estimation are insufficient to accurately measure bpm. For example a track with a BPM of 124 will always be rounded up to 125 when using madmom.features.tempo.TempoEstimationProcessor. 

I have ended up hacking around the outputs to generate more accurate estimates. 
```
import madmom, scipy.stats, numpy as np
beats = madmom.features.beats.RNNBeatProcessor()("test_audio.wav")
when_beats = madmom.features.beats.BeatTrackingProcessor(fps=100)(beats)
m_res = scipy.stats.linregress(np.arange(len(when_beats)),when_beats)

first_beat = m_res.intercept 
beat_step = m_res.slope

print("bpm = ", 60/beat_step)
```

this seems to be much more accurate. Often getting the bpm to within 0.01 of the actual bpm.
Is there another way within madmom to do this sort of accurate bpm determination?

I've got a working example of how I've used this here:
https://github.com/louischaman/PyBeatSync

**Comment by superbock** [comment]
This is on my TODO list basically forever. Right now there's no functionality included which gives more precise tempo estimates.

The reason why the tempo is inaccurate is simply because only the discrete bin of the beat interval histogram is considered. Given that the beat tracking algorithm works at 100 fps, there's a good chance that the most dominant interval is of by 10ms (or sometimes even more in case of stronger syncopation or swing).

Your solution is one way to improve the tempo estimate. I wanted to implement quadratic interpolation of beat interval clusters. I am not sure which one works better, I have to compare them. Expect this issue to be addressed within the net couple of weeks. If this is too late for you, please feel free to work on it and send in a PR.

**Comment by louischaman** [comment]
Thanks for the response keen to see your solution to this. The reason I'm not happy with my solution is that it uses the beat tracking processor which already makes use of the inaccurate tempo estimation which may have in turn meant less accurate beat tracking. I feel a cleaner solution may be more robust.

Without understanding the exact mechanisms behind how everything works I've thought of a way this might be solved more cleanly. 

Start by carrying out a similar exercise as is done for tempo estimation.

Instead of using only adjacent beats use all pairs or a random sample of all pairs if there are too many. 

Given these pair intervals construct a cost function of the beat interval with 

cost = Sum_over_pairs( abs( pair_interval - nearest_beat_estimate(pair_interval, beat_step)  ) ) 
where
nearest_beat_estimate(pair_interval, beat_step) = round_nearest( round_nearest(pair_interval, beat_step) , sample_spacing)
and for 100 fps we have
sample_spacing = 0.01

also: 
def round_nearest(x, round_to):
    return base * round(float(x)/base)

minimising this should give you an estimate that uses beats that are far apart (with more accuracy) as well as those close. If you plot the cost vs beat_step curve you will likely see multiple peaks that correspond to the bins in the histogram. 

Is this something like you were thinking?

My hack seems to work okay for now, but may look at trying this at some point.

**Comment by superbock** [comment]
I am not sure if I get this correctly, example code would be very appreciated.

My solution would be to use the highest peak of the tempo histogram and its 2 or 4 neighbouring bins and to a simple quadratic interpolation and picking the maximum of that function. This should work reasonably well hopefully.

**Comment by superbock** [comment]
Do you have the chance to compare #421 with your changes? It would help me a lot to see if my approach works as well as yours (or worse or better).

**Comment by aleksia123** [comment]
@louischaman @superbock 
Sorry this issue is a bit old, but i find the script that louis provides very accurate.

Is there a way to process multiple audio (.wav) files instead of providing one?

**Comment by superbock** [comment]
You can wrap everything in a callable (e.g. define a `Processor`) and add this to any pipeline producing beats.

Something like this:
```
class TempoRefinement(madmom.processors.Processor):

    def process(self, beats, **kwargs):
        m_res = scipy.stats.linregress(np.arange(len(beats)), beats)
        first_beat = m_res.intercept 
        beat_step = m_res.slope
        return 60 / beat_step
```

Simply plug this e.g. into [BeatDetector in line 97](https://github.com/CPJKU/madmom/blob/805c08e69b4390ce763c098474b2f96fab47bf60/bin/BeatDetector#L97) (using this one since it is used in the original code, but any other beat tracker works as well) as follows:

```
        beat_processor = BeatDetectionProcessor(**vars(args))
        tempo_refiner = TempoRefinement()
        out_processor = [beat_processor, tempo_refiner, write_tempo]
```

HTH

**Comment by superbock** [comment]
Just a quick update on this: #495 added code and models for our ISMIR 2019 paper which includes a better tempo estimation (code/models for the even better ISMIR 2020 paper to follow).
