### ISSUE TITLE
Hard coded tempo estimates

### ISSUE THREAD

**Issue by radkoff** [CPJKU/madmom#420]
Hi, I'm using madmom to detect downbeats. My workflow is RNNBeatProcessor -> BeatDetectionProcessor -> RNNBarProcessor -> DBNBarTrackingProcessor.

For some songs, I have BPM data from music brainz, and it looks to be accurate. Is there an easy way to incorporate this data in case it's more accurate than madmom's beat detection? I see BeatTrackingProcessor allows you to provide a tempo estimator, should I make my own TempoEstimationProcessor that returns the hard-coded tempo?

**Comment by superbock** [comment]
Of course you could change the code to accept a fixed bpm value (or interval in frames) instead of computing it automatically. But at the moment there's no argument you can pass that value.

Another way is (as you suggested) to code a "fake" `TempoEstimationProcessor` you can pass. You simply have implement the  `interval_histogram(activations)` method, which returns a histogram. In your case a simple tuple of two values (numpy arrays) would be enough. The first gives the height of the bins (you could choose an arbitrary value) and the second one being the interval in frames (at the given frame rate of 100fps).

You could also use the more advanced `DBNBeatTrackingProcessor` (instead of `
BeatDetectionProcessor`) and pass `min_bpm` and `max_bpm`.

Last but not least, have you tried `RNNDownBeatProcessor` and `DBNDownBeatTrackingProcessor`?

**Comment by radkoff** [comment]
Thanks for the min_bpm/max_bpm tip, I'll go with that.

I tried RNNDownBeatProcessor and DBNDownBeatTrackingProcessor a while back and remember not getting as good results, but I think this was a fluke, because now I see in the paper you were getting almost 90% accuracy for western music. I'll switch back.

**Comment by superbock** [comment]
Closing this issue, feel free to reopen if this things still don't work as expected.
