### ISSUE TITLE
Bug in quantize_events?

### ISSUE THREAD

**Issue by bjourne** [CPJKU/madmom#424]
I wonder if there isn't a off-by-one error in this function? Suppose I want to quantize one second of audio into 10 100 ms events.

```python
print(quantize_events(np.array([0.075]), 10, length = 10))
```
This causes the event at 75 ms to be put at index 1 due to the rounding. This is a little odd I think because it means that the first index covers 0 - 50 ms but the last 850 - 1000 ms.

**Comment by superbock** [comment]
It's true that this is a bit odd since it lacks proper documentation. This function dates back to when there was no distinction on where to put the origin of a frame. Back then it was centred around sample 0, i.e. the first index covers at 100fps only everything up to 50ms. Given that assumption, a length of 10 means everything up to 950ms, which is indeed a bit odd.

What would be needed is something similar to `origin` in the [`signal_frame` function](https://github.com/CPJKU/madmom/blob/master/madmom/audio/signal.py#L843).

This is no solution to your problem, but I hope that this explanation at least makes sense.

**Comment by bjourne** [comment]
I'm trying to follow the onset detection tutorial you directed me to earlier. I haven't thought deeply about it, but I wonder if this wouldn't negatively affect the training of a neural network? But perhaps the math works out fine anyway?

**Comment by superbock** [comment]
No it doesn't. I always use exactly this function to create the targets used for training. And even if the function would have an error, usually neural networks are quite good in learning this error as well.
