### ISSUE TITLE
'bands_per_octave' in LogarithmicFilterbank not implemented

### ISSUE THREAD

**Issue by maxifischer** [CPJKU/madmom#427]
First of all, great job with this library, helped a lot so far. I'm processing multiple music datasets with different properties. At the moment that causes me to get different shapes as an output from FilteredSpectrogram applied with the same parameters, presumably because of the 'bands_per_octave' parameter set to True in the used LogarithmicFilterbank.
I encountered a NotImplementedError for the parameter 'bands_per_octave'=False case in the LogarithmicFilterbank class. Is there any plan on how to implement it? And is anyone working on it already? Any help on how to tackle this problem is greatly appreciated.

**Comment by superbock** [comment]
The problem you're encountering is most likely due to different sample rates. Even implementing `bands_per_octave` so it can handle absolute values, will probably not solve it the correct way. It would result in the same number of bins, but lower sampling rates may change `fmax` and thus the bins correspond to different frequencies.

The only way to make sure that both the number of bins and the corresponding frequencies stay the same is to use the same sample rate. Try setting `sample_rate` to the most common sample rate (e.g. 44.1 kHz) and you should be set.

**Comment by maxifischer** [comment]
Thank you very much, setting the sample_rate solved the problem for me.
