### ISSUE TITLE
pickling / unpickling of data object

### ISSUE THREAD

**Issue by superbock** [CPJKU/madmom#79]
While working on issue #44, I discovered that not all information is recovered after pickling the data class objects. E.g. the `Spectrogram` does not save its `stft` sand `frames` attribute (which is totally ok, since it would require a lot of extra space), but in turn is not able to obtain the `bin_frequencies`, since it requires information about the `sample_rate` of the underlying audio. Possible solutions would be:

1) save the crucial information when pickling and use it after unpickling,
2) remove all the pickling of data classes functionality,
3) clearly state that not everything can be done after pickling data objects

Of course 1) is the desired solution, but if no-one uses the functionality right now (it is a leftover of how I prepared the data for training of neural networks) 2) would also be a valid solution. We can always re-add the functionality later if needed.

Any thoughts?

**Comment by fdlm** [comment]
**1)** would be nice, but we need to consider what to save and what not.
**2)** is also good. Since all the data classes are also numpy arrays, you can save the data using `np.save` if you want.
**3)** is the worst solution - keeping track of what is possible and what is not while using the library is cumbersome and weird.

I think if we are to implement pickling it should work seemlessly - meaning that if I pickle and unpickle the data object, it is *exactly* the same. This would require a lot of information (stft, frames, signal...) to be stored, as you mentioned. But if you want to save a stripped-down version of the data, you can always use `np.save`.

I would choose **2)** for now, we can add pickling later anyways without API break.

**Comment by superbock** [comment]
Ok, I chose option 2), since it is the safest right now. See PR #81.
